language: r
r:
  - 4.1.0
cache: packages
pandoc_version: 2.5
# dist: focal

latex: false

before_install:
  - sudo add-apt-repository -y ppa:cran/imagemagick
  - sudo apt-get -q update
  - sudo apt-get install -y libmagick++-dev

apt_packages:
  # - libmagick++-dev
  - libudunits2-dev
  - gdal-bin
  - libgdal1-dev
  - libproj-dev

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
