---
title: "Cronograma das aulas do curso"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE, cache=FALSE, warning=FALSE}
source("setup_knitr.R")
library(knitr)
library(kableExtra)
library(dplyr)
library(tidyr)
```

Abaixo está o cronograma inicial planejado para a disciplina. (**Revisado
em 2022-02-19**).

```{r, eval=FALSE, include=FALSE}
## Gera a lista com as datas de todas as aulas. O resultado do último
## comando pode ser copiado direto para o documento
datas1 <- seq.Date(as.Date("2019-08-06"), as.Date("2019-12-03"),
                   by = "week")
datas1 <- format.Date(datas1, format = "%d/%m")
datas2 <- seq.Date(as.Date("2019-08-09"), as.Date("2019-11-29"),
                   by = "week")
datas2 <- format.Date(datas2, format = "%d/%m")
cat(paste0("- **", datas1, " (Ter)", "**:\n", "- **",
           datas2, " (Sex)", "**:\n"))
```

```{r echo=FALSE, results='hide'}
dd <- read.table("misc/crono_rev.csv", header = TRUE, sep = ",")
str(dd)
```

```{r echo=FALSE}
dd |>
    dplyr::select(Data, Dia, Hora, Conteúdo) |>
    kable(align = "cccl") |>
    kable_styling(bootstrap_options = c("striped", "bordered")) |>
    column_spec(1, bold = TRUE) |>
    row_spec(c(11, 17, 24, 26, 27, 28), background = "lightgray")
```
