---
title: "Materiais"
output:
  html_document:
    toc: false
---

<div class="alert alert-danger" role="alert">
Para salvar os slides e páginas em PDF, abra no Google Chrome (ou
Chromium), aperte <kbd>Ctrl</kbd> <kbd>p</kbd> e selecione "Imprimir para
PDF".
</div>


<!-- De acordo com os itens do [cronograma](aulas.html): -->

- Introdução à Estatística Computacional II.
[Slides](slides/00_intro.html).
- Revisão de conceitos fundamentais da linguagem R. Ver capítulos 1, 2,
   3 e 5 da apostila [Estatística Comutacional com
   R](http://cursos.leg.ufpr.br/ecr/).
- Técnicas de programação: benchmarking, profiling, debugging e error
   handling. [Slides](slides/01_tecnicas.html).
- Geração de números aleatórios uniformes.
   [Slides](slides/02_RNG_uniforme.html).
   - [A note on random number
     generation](http://cran-r.c3sl.ufpr.br/web/packages/randtoolbox/vignettes/fullpres.pdf).
     Christophe Dutang e Diethelm Wuertz.
- Geração de números aleatórios não uniformes: método da transformação
  integral de probabilidade. [Slides](slides/03_RNG_inversa.html).
- Geração de números aleatórios não uniformes: método de aceitação e
  rejeição. [HTML](04_RNG_aceitacao.html).
- Geração de números aleatórios não uniformes: método da relação entre
  variáveis. [HTML](05_RNG_transform.html).
   - Implementar os métodos para aproximação do valor do $\pi$: método do
   círculo/quadrado e método da agullha de Buffon, com base nos
   materiais:
     - [Agulha de Buffon](https://www.cin.ufpe.br/~ldl/buffon.pdf) de
     Lauro Didier Lins
     - [Agulha de Buffon - Uma demonstração
     simples](https://www.e-publicacoes.uerj.br/index.php/cadmat/article/view/11896/9319) de R. C. Santos
     - [Métodos de Monte Carlo e Aproximações de $\pi$](misc/montecarlopi.pdf) de Fernando Henrique Ferraz Pereira da Rosa e colaboradores
- Integração de Monte Carlo. [HTML](06_MC_intro.html).
- Distribuições aproximadas baseadas em simulação de Monte Carlo.
  [HTML](07_MC_aprox.html).
- MCMC: Cadeias de Markov e algoritmo de Metropolis-Hastings.
  [HTML](08_MCMC.html).
- MCMC: Metropolis random walk e amostrador independente.
[HTML](08_MCMC.html).
- MCMC: Amostrador de Gibbs. [HTML](08_MCMC.html).
- Métodos de Monte Carlo para inferência estatística: estimadores e
suas propriedades. [HTML](09_MC_inf_estimacao.html).
- Testes de hipótese via simulação de Monte Carlo.
    [HTML](09_MC_inf_testes.html).
- Métodos de reamostragem: bootstrap. [HTML](10_bootstrap.html).
- Intervalos de confiança via bootstrap. [HTML](10_bootstrap.html).
- Jackknife e validação cruzada. [HTML](11_jackknife.html).
- Testes de permutação. [HTML](12_permutacao.html).

<!-- ### Páginas -->

<!-- - [Funções, objetos e classes](objetos-classes.html). -->
<!-- - [Indexação e seleção condicional](indexacao-selecao.html). -->
<!-- - [Programando com dados](programacao.html). -->
<!-- - Geração de números aleatórios não uniformes: [método -->
<!--   de aceitação e rejeição](04_RNG_aceitacao.html). -->
<!-- - Geração de números aleatórios não uniformes: [método -->
<!--  da relação entre variáveis](05_RNG_transform.html). -->
<!-- - [Integração de Monte Carlo](06_MC_intro.html). -->
<!-- - Distribuições aproximadas baseadas em [simulação de -->
<!--   Monte Carlo](07_MC_aprox.html). -->
<!-- - MCMC: [Metropolis random walk e amostrador -->
<!--   independente](08_MCMC-1.html). -->
<!-- - MCMC: [Cadeias de Markov e algoritmo de -->
<!--   Metropolis-Hastings](08_MCMC-2.html). -->
<!-- - Métodos de Monte Carlo para inferência estatística: -->
<!--   [estimação intervalar](09_MC_inf-1.html). -->
<!-- - Métodos de Monte Carlo para inferência estatística: -->
<!--   [estimação pontual](09_MC_inf-2.html). -->
<!-- - Testes de hipótese via [simulação de Monte Carlo](09_MC_inf-3.html). -->
<!-- - Métodos de reamostragem: [bootstrap](10_bootstrap.html). -->

<!-- ### Slides -->

<!-- - Introdução à Estatística Computacional II. -->
<!--   [HTML](slides/00_intro.html). -->
<!-- - Técnicas de programação. [HTML](slides/01_tecnicas.html). -->
<!-- - Geração de números aleatórios uniformes. -->
<!--   [HTML](slides/02_RNG_uniforme.html). -->
<!-- - Geração de números aleatórios não uniformes: método -->
<!--   da transformação integral de probabilidade. -->
<!--   [HTML](slides/03_RNG_inversa.html). -->

<!-- ### Scripts -->

<!-- - Técnicas de programação. [R](slides/01_tecnicas.R). -->
<!-- - MCMC: Metropolis random walk e amostrador independente. -->
<!-- [R](scripts/08_MCMC-1.R). -->

<!-- ## Materiais gerais -->

<!-- - [Estatística computacional com R](http://cursos.leg.ufpr.br/ecr/) -->
<!--   (apostila da disciplina de Estatística Computacional I). -->
<!-- - Materiais da [oferta anterior](http://leg.ufpr.br/~walmes/ensino/EC2/) -->
<!--   (Prof. Walmes). -->
