name: deploy

# Only run this when the main branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the site, and pushes it to `gh-pages``
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install R
    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()

    # - name: Install R dependencies
    #   run: |
    #     Rscript setup.R

    # Build the site
    - name: Build the site
      run: |
        Rscript -e "rmarkdown::render_site()"

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
